# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jakub\Visual Studio Code\Game of 40\a_game_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_a_game_menu(object):
    def setupUi(self, a_game_menu):
        a_game_menu.setObjectName("a_game_menu")
        a_game_menu.resize(400, 300)
        self.a_game_menu_player_name = QtWidgets.QLabel(a_game_menu)
        self.a_game_menu_player_name.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.a_game_menu_player_name.setObjectName("a_game_menu_player_name")
        self.a_game_menu_turn_label = QtWidgets.QLabel(a_game_menu)
        self.a_game_menu_turn_label.setGeometry(QtCore.QRect(170, 20, 100, 13))
        self.a_game_menu_turn_label.setObjectName("a_game_menu_turn_label")
        self.a_game_menu_ai_name = QtWidgets.QLabel(a_game_menu)
        self.a_game_menu_ai_name.setGeometry(QtCore.QRect(310, 20, 47, 13))
        self.a_game_menu_ai_name.setObjectName("a_game_menu_ai_name")
        self.label_4 = QtWidgets.QLabel(a_game_menu)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(a_game_menu)
        self.label_5.setGeometry(QtCore.QRect(310, 50, 47, 13))
        self.label_5.setObjectName("label_5")
        self.a_game_menu_player_score = QtWidgets.QLabel(a_game_menu)
        self.a_game_menu_player_score.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.a_game_menu_player_score.setObjectName("a_game_menu_player_score")
        self.a_game_menu_ai_score = QtWidgets.QLabel(a_game_menu)
        self.a_game_menu_ai_score.setGeometry(QtCore.QRect(310, 80, 47, 13))
        self.a_game_menu_ai_score.setObjectName("a_game_menu_ai_score")
        self.label_8 = QtWidgets.QLabel(a_game_menu)
        self.label_8.setGeometry(QtCore.QRect(30, 110, 61, 16))
        self.label_8.setObjectName("label_8")
        self.a_game_menu_player_dicescore = QtWidgets.QLabel(a_game_menu)
        self.a_game_menu_player_dicescore.setGeometry(QtCore.QRect(30, 140, 47, 13))
        self.a_game_menu_player_dicescore.setObjectName("a_game_menu_player_dicescore")
        self.label_10 = QtWidgets.QLabel(a_game_menu)
        self.label_10.setGeometry(QtCore.QRect(310, 110, 61, 16))
        self.label_10.setObjectName("label_10")
        self.a_game_menu_ai_dicescore = QtWidgets.QLabel(a_game_menu)
        self.a_game_menu_ai_dicescore.setGeometry(QtCore.QRect(310, 140, 47, 13))
        self.a_game_menu_ai_dicescore.setObjectName("a_game_menu_ai_dicescore")
        self.a_game_menu_player_rollhistory = QtWidgets.QPushButton(a_game_menu)
        self.a_game_menu_player_rollhistory.setGeometry(QtCore.QRect(20, 170, 75, 23))
        self.a_game_menu_player_rollhistory.setObjectName("a_game_menu_player_rollhistory")
        self.a_game_menu_ai_rollhistory = QtWidgets.QPushButton(a_game_menu)
        self.a_game_menu_ai_rollhistory.setGeometry(QtCore.QRect(300, 170, 75, 23))
        self.a_game_menu_ai_rollhistory.setObjectName("a_game_menu_ai_rollhistory")
        self.a_game_menu_roll = QtWidgets.QPushButton(a_game_menu)
        self.a_game_menu_roll.setGeometry(QtCore.QRect(20, 260, 75, 23))
        self.a_game_menu_roll.setObjectName("a_game_menu_roll")
        self.a_game_menu_endturn = QtWidgets.QPushButton(a_game_menu)
        self.a_game_menu_endturn.setGeometry(QtCore.QRect(160, 260, 75, 23))
        self.a_game_menu_endturn.setObjectName("a_game_menu_endturn")
        self.a_game_menu_end = QtWidgets.QPushButton(a_game_menu)
        self.a_game_menu_end.setGeometry(QtCore.QRect(300, 260, 75, 23))
        self.a_game_menu_end.setObjectName("a_game_menu_end")
        self.a_game_menu_dicescore = QtWidgets.QLabel(a_game_menu)
        self.a_game_menu_dicescore.setGeometry(QtCore.QRect(170, 110, 120, 16))
        self.a_game_menu_dicescore.setObjectName("a_game_menu_dicescore")

        self.retranslateUi(a_game_menu)
        QtCore.QMetaObject.connectSlotsByName(a_game_menu)

    def retranslateUi(self, a_game_menu):
        _translate = QtCore.QCoreApplication.translate
        a_game_menu.setWindowTitle(_translate("a_game_menu", "Dialog"))
        self.a_game_menu_player_name.setText(_translate("a_game_menu", "TextLabel"))
        self.a_game_menu_turn_label.setText(_translate("a_game_menu", "TextLabel"))
        self.a_game_menu_ai_name.setText(_translate("a_game_menu", "TextLabel"))
        self.label_4.setText(_translate("a_game_menu", "Score:"))
        self.label_5.setText(_translate("a_game_menu", "Score"))
        self.a_game_menu_player_score.setText(_translate("a_game_menu", "0"))
        self.a_game_menu_ai_score.setText(_translate("a_game_menu", "0"))
        self.label_8.setText(_translate("a_game_menu", "Dice Score:"))
        self.a_game_menu_player_dicescore.setText(_translate("a_game_menu", "0"))
        self.label_10.setText(_translate("a_game_menu", "Dice Score:"))
        self.a_game_menu_ai_dicescore.setText(_translate("a_game_menu", "0"))
        self.a_game_menu_player_rollhistory.setText(_translate("a_game_menu", "Roll History"))
        self.a_game_menu_ai_rollhistory.setText(_translate("a_game_menu", "Roll History"))
        self.a_game_menu_roll.setText(_translate("a_game_menu", "Roll"))
        self.a_game_menu_endturn.setText(_translate("a_game_menu", "End Turn"))
        self.a_game_menu_end.setText(_translate("a_game_menu", "End"))
        self.a_game_menu_dicescore.setText(_translate("a_game_menu", "You rolled: _ "))
