# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jakub\Visual Studio Code\Game of 40\choose_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose_menu(object):
    def setupUi(self, choose_menu):
        choose_menu.setObjectName("choose_menu")
        choose_menu.resize(400, 300)
        self.choose_menu_label = QtWidgets.QLabel(choose_menu)
        self.choose_menu_label.setGeometry(QtCore.QRect(40, 20, 331, 91))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(28)
        self.choose_menu_label.setFont(font)
        self.choose_menu_label.setObjectName("choose_menu_label")
        self.choose_menu_ai_choose = QtWidgets.QComboBox(choose_menu)
        self.choose_menu_ai_choose.setGeometry(QtCore.QRect(250, 180, 69, 22))
        self.choose_menu_ai_choose.setObjectName("choose_menu_ai_choose")
        self.choose_menu_ai_choose.addItem("")
        self.choose_menu_ai_choose.addItem("")
        self.choose_menu_ai_choose.addItem("")
        self.choose_menu_ai_choose.addItem("")
        self.choose_menu_back = QtWidgets.QPushButton(choose_menu)
        self.choose_menu_back.setGeometry(QtCore.QRect(30, 240, 75, 23))
        self.choose_menu_back.setObjectName("choose_menu_back")
        self.choose_menu_vs_player = QtWidgets.QPushButton(choose_menu)
        self.choose_menu_vs_player.setGeometry(QtCore.QRect(140, 140, 75, 23))
        self.choose_menu_vs_player.setObjectName("choose_menu_vs_player")
        self.choose_menu_vs_ai = QtWidgets.QPushButton(choose_menu)
        self.choose_menu_vs_ai.setGeometry(QtCore.QRect(140, 180, 75, 23))
        self.choose_menu_vs_ai.setObjectName("choose_menu_vs_ai")

        self.retranslateUi(choose_menu)
        QtCore.QMetaObject.connectSlotsByName(choose_menu)
        choose_menu.setTabOrder(self.choose_menu_vs_player, self.choose_menu_vs_ai)
        choose_menu.setTabOrder(self.choose_menu_vs_ai, self.choose_menu_ai_choose)
        choose_menu.setTabOrder(self.choose_menu_ai_choose, self.choose_menu_back)

    def retranslateUi(self, choose_menu):
        _translate = QtCore.QCoreApplication.translate
        choose_menu.setWindowTitle(_translate("choose_menu", "Dialog"))
        self.choose_menu_label.setText(_translate("choose_menu", "Choose Gamemode"))
        self.choose_menu_ai_choose.setItemText(0, _translate("choose_menu", "Easy"))
        self.choose_menu_ai_choose.setItemText(1, _translate("choose_menu", "Medium"))
        self.choose_menu_ai_choose.setItemText(2, _translate("choose_menu", "Hard"))
        self.choose_menu_ai_choose.setItemText(3, _translate("choose_menu", "Impossible"))
        self.choose_menu_back.setText(_translate("choose_menu", "Back"))
        self.choose_menu_vs_player.setText(_translate("choose_menu", "Versus Player"))
        self.choose_menu_vs_ai.setText(_translate("choose_menu", "Versus AI"))
