# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jakub\Visual Studio Code\Game of 40\history_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_history_menu(object):
    def setupUi(self, history_menu):
        history_menu.setObjectName("history_menu")
        history_menu.resize(400, 300)
        self.history_menu_scrollarea = QtWidgets.QScrollArea(history_menu)
        self.history_menu_scrollarea.setGeometry(QtCore.QRect(-1, -1, 401, 251))
        self.history_menu_scrollarea.setWidgetResizable(True)
        self.history_menu_scrollarea.setObjectName("history_menu_scrollarea")
        self.history_menu_scrollarea_content = QtWidgets.QWidget()
        self.history_menu_scrollarea_content.setGeometry(QtCore.QRect(0, 0, 399, 249))
        self.history_menu_scrollarea_content.setObjectName("history_menu_scrollarea_content")
        self.history_menu_scrollarea.setWidget(self.history_menu_scrollarea_content)
        self.history_menu_back = QtWidgets.QPushButton(history_menu)
        self.history_menu_back.setGeometry(QtCore.QRect(160, 260, 75, 23))
        self.history_menu_back.setObjectName("history_menu_back")

        self.retranslateUi(history_menu)
        QtCore.QMetaObject.connectSlotsByName(history_menu)

    def retranslateUi(self, history_menu):
        _translate = QtCore.QCoreApplication.translate
        history_menu.setWindowTitle(_translate("history_menu", "Dialog"))
        self.history_menu_back.setText(_translate("history_menu", "Back"))
