# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jakub\Visual Studio Code\Game of 40\main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_menu(object):
    def setupUi(self, main_menu):
        main_menu.setObjectName("main_menu")
        main_menu.resize(400, 300)
        self.main_menu_label = QtWidgets.QLabel(main_menu)
        self.main_menu_label.setGeometry(QtCore.QRect(110, 20, 201, 91))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(26)
        self.main_menu_label.setFont(font)
        self.main_menu_label.setObjectName("main_menu_label")
        self.main_menu_start = QtWidgets.QPushButton(main_menu)
        self.main_menu_start.setGeometry(QtCore.QRect(50, 200, 75, 23))
        self.main_menu_start.setObjectName("main_menu_start")
        self.main_menu_exit = QtWidgets.QPushButton(main_menu)
        self.main_menu_exit.setGeometry(QtCore.QRect(250, 200, 75, 23))
        self.main_menu_exit.setObjectName("main_menu_exit")

        self.retranslateUi(main_menu)
        QtCore.QMetaObject.connectSlotsByName(main_menu)

    def retranslateUi(self, main_menu):
        _translate = QtCore.QCoreApplication.translate
        main_menu.setWindowTitle(_translate("main_menu", "Dialog"))
        self.main_menu_label.setText(_translate("main_menu", "Game of 40"))
        self.main_menu_start.setText(_translate("main_menu", "Start"))
        self.main_menu_exit.setText(_translate("main_menu", "Exit"))
