# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jakub\Visual Studio Code\Game of 40\player_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_player_menu(object):
    def setupUi(self, player_menu):
        player_menu.setObjectName("player_menu")
        player_menu.resize(400, 300)
        self.player_menu_label = QtWidgets.QLabel(player_menu)
        self.player_menu_label.setGeometry(QtCore.QRect(60, 30, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(26)
        self.player_menu_label.setFont(font)
        self.player_menu_label.setObjectName("player_menu_label")
        self.player_menu_player1_lineedit = QtWidgets.QLineEdit(player_menu)
        self.player_menu_player1_lineedit.setGeometry(QtCore.QRect(70, 110, 113, 20))
        self.player_menu_player1_lineedit.setObjectName("player_menu_player1_lineedit")
        self.player_menu_player2_lineedit = QtWidgets.QLineEdit(player_menu)
        self.player_menu_player2_lineedit.setGeometry(QtCore.QRect(70, 150, 113, 20))
        self.player_menu_player2_lineedit.setObjectName("player_menu_player2_lineedit")
        self.player_menu_player1_label = QtWidgets.QLabel(player_menu)
        self.player_menu_player1_label.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.player_menu_player1_label.setObjectName("player_menu_player1_label")
        self.player_menu_player1_label_2 = QtWidgets.QLabel(player_menu)
        self.player_menu_player1_label_2.setGeometry(QtCore.QRect(20, 150, 47, 13))
        self.player_menu_player1_label_2.setObjectName("player_menu_player1_label_2")
        self.player_menu_start = QtWidgets.QPushButton(player_menu)
        self.player_menu_start.setGeometry(QtCore.QRect(40, 250, 75, 23))
        self.player_menu_start.setObjectName("player_menu_start")
        self.player_menu_back = QtWidgets.QPushButton(player_menu)
        self.player_menu_back.setGeometry(QtCore.QRect(290, 250, 75, 23))
        self.player_menu_back.setObjectName("player_menu_back")

        self.retranslateUi(player_menu)
        QtCore.QMetaObject.connectSlotsByName(player_menu)

    def retranslateUi(self, player_menu):
        _translate = QtCore.QCoreApplication.translate
        player_menu.setWindowTitle(_translate("player_menu", "Dialog"))
        self.player_menu_label.setText(_translate("player_menu", "Choose your names"))
        self.player_menu_player1_label.setText(_translate("player_menu", "Player 1:"))
        self.player_menu_player1_label_2.setText(_translate("player_menu", "Player 2:"))
        self.player_menu_start.setText(_translate("player_menu", "Start"))
        self.player_menu_back.setText(_translate("player_menu", "Back"))
