# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jakub\Visual Studio Code\Game of 40\p_game_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_p_game_menu(object):
    def setupUi(self, p_game_menu):
        p_game_menu.setObjectName("p_game_menu")
        p_game_menu.resize(400, 300)
        self.p_game_menu_player1_name = QtWidgets.QLabel(p_game_menu)
        self.p_game_menu_player1_name.setGeometry(QtCore.QRect(30, 20, 100, 13))
        self.p_game_menu_player1_name.setObjectName("p_game_menu_player1_name")
        self.p_game_menu_turn_label = QtWidgets.QLabel(p_game_menu)
        self.p_game_menu_turn_label.setGeometry(QtCore.QRect(170, 20, 100, 13))
        self.p_game_menu_turn_label.setObjectName("p_game_menu_turn_label")
        self.p_game_menu_player2_name = QtWidgets.QLabel(p_game_menu)
        self.p_game_menu_player2_name.setGeometry(QtCore.QRect(310, 20, 100, 13))
        self.p_game_menu_player2_name.setObjectName("p_game_menu_player2_name")
        self.label_4 = QtWidgets.QLabel(p_game_menu)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(p_game_menu)
        self.label_5.setGeometry(QtCore.QRect(310, 50, 47, 13))
        self.label_5.setObjectName("label_5")
        self.p_game_menu_player1_wins = QtWidgets.QLabel(p_game_menu)
        self.p_game_menu_player1_wins.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.p_game_menu_player1_wins.setObjectName("p_game_menu_player1_wins")
        self.p_game_menu_player2_wins = QtWidgets.QLabel(p_game_menu)
        self.p_game_menu_player2_wins.setGeometry(QtCore.QRect(310, 80, 47, 13))
        self.p_game_menu_player2_wins.setObjectName("p_game_menu_player2_wins")
        self.label_8 = QtWidgets.QLabel(p_game_menu)
        self.label_8.setGeometry(QtCore.QRect(30, 110, 61, 16))
        self.label_8.setObjectName("label_8")
        self.p_game_menu_player1_score = QtWidgets.QLabel(p_game_menu)
        self.p_game_menu_player1_score.setGeometry(QtCore.QRect(30, 140, 47, 13))
        self.p_game_menu_player1_score.setObjectName("p_game_menu_player1_score")
        self.label_10 = QtWidgets.QLabel(p_game_menu)
        self.label_10.setGeometry(QtCore.QRect(310, 110, 61, 16))
        self.label_10.setObjectName("label_10")
        self.p_game_menu_player2_score = QtWidgets.QLabel(p_game_menu)
        self.p_game_menu_player2_score.setGeometry(QtCore.QRect(310, 140, 47, 13))
        self.p_game_menu_player2_score.setObjectName("p_game_menu_player2_score")
        self.p_game_menu_player1_history = QtWidgets.QPushButton(p_game_menu)
        self.p_game_menu_player1_history.setGeometry(QtCore.QRect(20, 170, 75, 23))
        self.p_game_menu_player1_history.setObjectName("p_game_menu_player1_history")
        self.p_game_menu_player2_history = QtWidgets.QPushButton(p_game_menu)
        self.p_game_menu_player2_history.setGeometry(QtCore.QRect(300, 170, 75, 23))
        self.p_game_menu_player2_history.setObjectName("p_game_menu_player2_history")
        self.p_game_menu_roll = QtWidgets.QPushButton(p_game_menu)
        self.p_game_menu_roll.setGeometry(QtCore.QRect(20, 260, 75, 23))
        self.p_game_menu_roll.setObjectName("p_game_menu_roll")
        self.p_game_menu_endturn = QtWidgets.QPushButton(p_game_menu)
        self.p_game_menu_endturn.setGeometry(QtCore.QRect(160, 260, 75, 23))
        self.p_game_menu_endturn.setObjectName("p_game_menu_endturn")
        self.p_game_menu_exit = QtWidgets.QPushButton(p_game_menu)
        self.p_game_menu_exit.setGeometry(QtCore.QRect(300, 260, 75, 23))
        self.p_game_menu_exit.setObjectName("p_game_menu_exit")
        self.p_game_menu_currentdice = QtWidgets.QLabel(p_game_menu)
        self.p_game_menu_currentdice.setGeometry(QtCore.QRect(170, 110, 60, 13))
        self.p_game_menu_currentdice.setObjectName("p_game_menu_currentdice")

        self.retranslateUi(p_game_menu)
        QtCore.QMetaObject.connectSlotsByName(p_game_menu)

    def retranslateUi(self, p_game_menu):
        _translate = QtCore.QCoreApplication.translate
        p_game_menu.setWindowTitle(_translate("p_game_menu", "Dialog"))
        self.p_game_menu_player1_name.setText(_translate("p_game_menu", "TextLabel"))
        self.p_game_menu_turn_label.setText(_translate("p_game_menu", "TextLabel"))
        self.p_game_menu_player2_name.setText(_translate("p_game_menu", "TextLabel"))
        self.label_4.setText(_translate("p_game_menu", "Wins:"))
        self.label_5.setText(_translate("p_game_menu", "Wins:"))
        self.p_game_menu_player1_wins.setText(_translate("p_game_menu", "0"))
        self.p_game_menu_player2_wins.setText(_translate("p_game_menu", "0"))
        self.label_8.setText(_translate("p_game_menu", "Dice Score:"))
        self.p_game_menu_player1_score.setText(_translate("p_game_menu", "0"))
        self.label_10.setText(_translate("p_game_menu", "Dice Score:"))
        self.p_game_menu_player2_score.setText(_translate("p_game_menu", "0"))
        self.p_game_menu_player1_history.setText(_translate("p_game_menu", "Roll History"))
        self.p_game_menu_player2_history.setText(_translate("p_game_menu", "Roll History"))
        self.p_game_menu_roll.setText(_translate("p_game_menu", "Roll"))
        self.p_game_menu_endturn.setText(_translate("p_game_menu", "End Turn"))
        self.p_game_menu_exit.setText(_translate("p_game_menu", "Exit"))
        self.p_game_menu_currentdice.setText(_translate("p_game_menu", "You rolled: _" ))
