# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jakub\Visual Studio Code\Game of 40\win_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_menu(object):
    def setupUi(self, win_menu):
        win_menu.setObjectName("win_menu")
        win_menu.resize(400, 300)
        self.win_menu_label = QtWidgets.QLabel(win_menu)
        self.win_menu_label.setGeometry(QtCore.QRect(110, 30, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(26)
        self.win_menu_label.setFont(font)
        self.win_menu_label.setObjectName("win_menu_label")
        self.win_menu_continue = QtWidgets.QPushButton(win_menu)
        self.win_menu_continue.setGeometry(QtCore.QRect(150, 160, 75, 23))
        self.win_menu_continue.setObjectName("win_menu_continue")
        self.win_menu_exit = QtWidgets.QPushButton(win_menu)
        self.win_menu_exit.setGeometry(QtCore.QRect(150, 210, 75, 23))
        self.win_menu_exit.setObjectName("win_menu_exit")

        self.retranslateUi(win_menu)
        QtCore.QMetaObject.connectSlotsByName(win_menu)

    def retranslateUi(self, win_menu):
        _translate = QtCore.QCoreApplication.translate
        win_menu.setWindowTitle(_translate("win_menu", "Dialog"))
        self.win_menu_label.setText(_translate("win_menu", "TextLabel"))
        self.win_menu_continue.setText(_translate("win_menu", "Continue"))
        self.win_menu_exit.setText(_translate("win_menu", "Exit"))
